-- 대여 시작일 2022년 9월에 속하는 기록 중
-- 대여 기간이 30일 이상이면 장기대여 
-- 그렇지 않으면 단기 대여로 표시(RENT_TYPE)을 추가 후 출력
SELECT HISTORY_ID, CAR_ID, 
DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, 
DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE, 
CASE 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 29 THEN '단기 대여'
    ELSE '장기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-09-01' AND '2022-09-30'
ORDER BY HISTORY_ID DESC;