-- 몇시 입양이 가장 활발하게 일어나는지 알아보려 함
-- 09:00부터 19:59까지 각 시간대별 입양이 몇 건 발생했는지 조회
SELECT 
HOUR(DATETIME) AS HOUR, 
COUNT(*) AS COUNT 
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;