-- 2021년 출판된 '인문' 카테고리 도서 리스트 출력
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31' 
AND CATEGORY LIKE '인문'
ORDER BY PUBLISHED_DATE;