-- 2022년 10월 작성된 
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자_ID, 내용, 작성일 조회
SELECT 
B.TITLE, 
B.BOARD_ID, 
R.REPLY_ID, 
R.WRITER_ID, 
R.CONTENTS, 
DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE (
    B.BOARD_ID = R.BOARD_ID AND
    B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
)
ORDER BY CREATED_DATE, TITLE;